/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shbus.easybus.front;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class channelServiceConstants {

  /**
   * 上海车站代码-白莲泾站
   */
  public static final String UNIT_ID_BLJZ = "2000000022";

  /**
   * 上海车站代码-巴士长运
   */
  public static final String UNIT_ID_BSCY = "2000000009";

  /**
   * 上海车站代码-巴士南汇
   */
  public static final String UNIT_ID_BSNH = "2000000008";

  /**
   * 上海车站代码-巴士吴淞
   */
  public static final String UNIT_ID_BSWS = "2000000013";

  /**
   * 上海车站代码-崇明站
   */
  public static final String UNIT_ID_CMZ = "da8dc554-6374-4915-a0ea-39e7f6b5c3b0";

  /**
   * 上海车站代码-长兴站
   */
  public static final String UNIT_ID_CXZ = "ee4cbdee-c1e8-4db7-8bb0-d62ea2bb176b";

  /**
   * 上海车站代码-强生高桥
   */
  public static final String UNIT_ID_QSGQ = "2000000033";

  /**
   * 上海车站代码-交运高速
   */
  public static final String UNIT_ID_JYGS = "2000000017";

  /**
   * 上海车站代码-客运北站
   */
  public static final String UNIT_ID_KYBZ = "59dc6171-e0e6-48f1-930c-2f4f4e4368bf";

  /**
   * 上海车站代码-客运南站
   */
  public static final String UNIT_ID_KYNZ = "2000000021";

  /**
   * 上海车站代码-客运西站
   */
  public static final String UNIT_ID_KYXZ = "1e49c163-394d-41e2-a647-e639b273beea";

  /**
   * 上海车站代码-客运总站
   */
  public static final String UNIT_ID_KYZZ = "2000000023";

  /**
   * 上海车站代码-浦江站
   */
  public static final String UNIT_ID_PJZ = "2000000015";

  /**
   * 上海车站代码-强生长途
   */
  public static final String UNIT_ID_QSCT = "2000000005";

}
