/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shbus.easybus.thrift.front;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-31")
public class ChangeTicketRecStatusToYesResp implements org.apache.thrift.TBase<ChangeTicketRecStatusToYesResp, ChangeTicketRecStatusToYesResp._Fields>, java.io.Serializable, Cloneable, Comparable<ChangeTicketRecStatusToYesResp> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ChangeTicketRecStatusToYesResp");

  private static final org.apache.thrift.protocol.TField BUS_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("busError", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ChangeTicketRecStatusToYesRespStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ChangeTicketRecStatusToYesRespTupleSchemeFactory());
  }

  /**
   * 错误信息
   */
  public BusError busError; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 错误信息
     */
    BUS_ERROR((short)1, "busError");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BUS_ERROR
          return BUS_ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BUS_ERROR, new org.apache.thrift.meta_data.FieldMetaData("busError", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BusError.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ChangeTicketRecStatusToYesResp.class, metaDataMap);
  }

  public ChangeTicketRecStatusToYesResp() {
  }

  public ChangeTicketRecStatusToYesResp(
    BusError busError)
  {
    this();
    this.busError = busError;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ChangeTicketRecStatusToYesResp(ChangeTicketRecStatusToYesResp other) {
    if (other.isSetBusError()) {
      this.busError = new BusError(other.busError);
    }
  }

  public ChangeTicketRecStatusToYesResp deepCopy() {
    return new ChangeTicketRecStatusToYesResp(this);
  }

  @Override
  public void clear() {
    this.busError = null;
  }

  /**
   * 错误信息
   */
  public BusError getBusError() {
    return this.busError;
  }

  /**
   * 错误信息
   */
  public ChangeTicketRecStatusToYesResp setBusError(BusError busError) {
    this.busError = busError;
    return this;
  }

  public void unsetBusError() {
    this.busError = null;
  }

  /** Returns true if field busError is set (has been assigned a value) and false otherwise */
  public boolean isSetBusError() {
    return this.busError != null;
  }

  public void setBusErrorIsSet(boolean value) {
    if (!value) {
      this.busError = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BUS_ERROR:
      if (value == null) {
        unsetBusError();
      } else {
        setBusError((BusError)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BUS_ERROR:
      return getBusError();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BUS_ERROR:
      return isSetBusError();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ChangeTicketRecStatusToYesResp)
      return this.equals((ChangeTicketRecStatusToYesResp)that);
    return false;
  }

  public boolean equals(ChangeTicketRecStatusToYesResp that) {
    if (that == null)
      return false;

    boolean this_present_busError = true && this.isSetBusError();
    boolean that_present_busError = true && that.isSetBusError();
    if (this_present_busError || that_present_busError) {
      if (!(this_present_busError && that_present_busError))
        return false;
      if (!this.busError.equals(that.busError))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_busError = true && (isSetBusError());
    list.add(present_busError);
    if (present_busError)
      list.add(busError);

    return list.hashCode();
  }

  @Override
  public int compareTo(ChangeTicketRecStatusToYesResp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBusError()).compareTo(other.isSetBusError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBusError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.busError, other.busError);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ChangeTicketRecStatusToYesResp(");
    boolean first = true;

    sb.append("busError:");
    if (this.busError == null) {
      sb.append("null");
    } else {
      sb.append(this.busError);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (busError != null) {
      busError.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ChangeTicketRecStatusToYesRespStandardSchemeFactory implements SchemeFactory {
    public ChangeTicketRecStatusToYesRespStandardScheme getScheme() {
      return new ChangeTicketRecStatusToYesRespStandardScheme();
    }
  }

  private static class ChangeTicketRecStatusToYesRespStandardScheme extends StandardScheme<ChangeTicketRecStatusToYesResp> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ChangeTicketRecStatusToYesResp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BUS_ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.busError = new BusError();
              struct.busError.read(iprot);
              struct.setBusErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ChangeTicketRecStatusToYesResp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.busError != null) {
        oprot.writeFieldBegin(BUS_ERROR_FIELD_DESC);
        struct.busError.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ChangeTicketRecStatusToYesRespTupleSchemeFactory implements SchemeFactory {
    public ChangeTicketRecStatusToYesRespTupleScheme getScheme() {
      return new ChangeTicketRecStatusToYesRespTupleScheme();
    }
  }

  private static class ChangeTicketRecStatusToYesRespTupleScheme extends TupleScheme<ChangeTicketRecStatusToYesResp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ChangeTicketRecStatusToYesResp struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBusError()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetBusError()) {
        struct.busError.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ChangeTicketRecStatusToYesResp struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.busError = new BusError();
        struct.busError.read(iprot);
        struct.setBusErrorIsSet(true);
      }
    }
  }

}

