/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shbus.easybus.thrift.front;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
/**
 * 查询车次信息 响应
 */
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-31")
public class QueryBusResp implements org.apache.thrift.TBase<QueryBusResp, QueryBusResp._Fields>, java.io.Serializable, Cloneable, Comparable<QueryBusResp> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryBusResp");

  private static final org.apache.thrift.protocol.TField BUS_ALL_INFO_VOLIST_FIELD_DESC = new org.apache.thrift.protocol.TField("busAllInfoVOList", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField BUS_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("busError", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryBusRespStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryBusRespTupleSchemeFactory());
  }

  /**
   * 车次信息列表
   */
  public Set<BusAllInfoVO> busAllInfoVOList; // required
  /**
   * 错误信息
   */
  public BusError busError; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 车次信息列表
     */
    BUS_ALL_INFO_VOLIST((short)1, "busAllInfoVOList"),
    /**
     * 错误信息
     */
    BUS_ERROR((short)2, "busError");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BUS_ALL_INFO_VOLIST
          return BUS_ALL_INFO_VOLIST;
        case 2: // BUS_ERROR
          return BUS_ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BUS_ALL_INFO_VOLIST, new org.apache.thrift.meta_data.FieldMetaData("busAllInfoVOList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BusAllInfoVO.class))));
    tmpMap.put(_Fields.BUS_ERROR, new org.apache.thrift.meta_data.FieldMetaData("busError", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BusError.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryBusResp.class, metaDataMap);
  }

  public QueryBusResp() {
  }

  public QueryBusResp(
    Set<BusAllInfoVO> busAllInfoVOList,
    BusError busError)
  {
    this();
    this.busAllInfoVOList = busAllInfoVOList;
    this.busError = busError;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryBusResp(QueryBusResp other) {
    if (other.isSetBusAllInfoVOList()) {
      Set<BusAllInfoVO> __this__busAllInfoVOList = new HashSet<BusAllInfoVO>(other.busAllInfoVOList.size());
      for (BusAllInfoVO other_element : other.busAllInfoVOList) {
        __this__busAllInfoVOList.add(new BusAllInfoVO(other_element));
      }
      this.busAllInfoVOList = __this__busAllInfoVOList;
    }
    if (other.isSetBusError()) {
      this.busError = new BusError(other.busError);
    }
  }

  public QueryBusResp deepCopy() {
    return new QueryBusResp(this);
  }

  @Override
  public void clear() {
    this.busAllInfoVOList = null;
    this.busError = null;
  }

  public int getBusAllInfoVOListSize() {
    return (this.busAllInfoVOList == null) ? 0 : this.busAllInfoVOList.size();
  }

  public java.util.Iterator<BusAllInfoVO> getBusAllInfoVOListIterator() {
    return (this.busAllInfoVOList == null) ? null : this.busAllInfoVOList.iterator();
  }

  public void addToBusAllInfoVOList(BusAllInfoVO elem) {
    if (this.busAllInfoVOList == null) {
      this.busAllInfoVOList = new HashSet<BusAllInfoVO>();
    }
    this.busAllInfoVOList.add(elem);
  }

  /**
   * 车次信息列表
   */
  public Set<BusAllInfoVO> getBusAllInfoVOList() {
    return this.busAllInfoVOList;
  }

  /**
   * 车次信息列表
   */
  public QueryBusResp setBusAllInfoVOList(Set<BusAllInfoVO> busAllInfoVOList) {
    this.busAllInfoVOList = busAllInfoVOList;
    return this;
  }

  public void unsetBusAllInfoVOList() {
    this.busAllInfoVOList = null;
  }

  /** Returns true if field busAllInfoVOList is set (has been assigned a value) and false otherwise */
  public boolean isSetBusAllInfoVOList() {
    return this.busAllInfoVOList != null;
  }

  public void setBusAllInfoVOListIsSet(boolean value) {
    if (!value) {
      this.busAllInfoVOList = null;
    }
  }

  /**
   * 错误信息
   */
  public BusError getBusError() {
    return this.busError;
  }

  /**
   * 错误信息
   */
  public QueryBusResp setBusError(BusError busError) {
    this.busError = busError;
    return this;
  }

  public void unsetBusError() {
    this.busError = null;
  }

  /** Returns true if field busError is set (has been assigned a value) and false otherwise */
  public boolean isSetBusError() {
    return this.busError != null;
  }

  public void setBusErrorIsSet(boolean value) {
    if (!value) {
      this.busError = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BUS_ALL_INFO_VOLIST:
      if (value == null) {
        unsetBusAllInfoVOList();
      } else {
        setBusAllInfoVOList((Set<BusAllInfoVO>)value);
      }
      break;

    case BUS_ERROR:
      if (value == null) {
        unsetBusError();
      } else {
        setBusError((BusError)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BUS_ALL_INFO_VOLIST:
      return getBusAllInfoVOList();

    case BUS_ERROR:
      return getBusError();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BUS_ALL_INFO_VOLIST:
      return isSetBusAllInfoVOList();
    case BUS_ERROR:
      return isSetBusError();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryBusResp)
      return this.equals((QueryBusResp)that);
    return false;
  }

  public boolean equals(QueryBusResp that) {
    if (that == null)
      return false;

    boolean this_present_busAllInfoVOList = true && this.isSetBusAllInfoVOList();
    boolean that_present_busAllInfoVOList = true && that.isSetBusAllInfoVOList();
    if (this_present_busAllInfoVOList || that_present_busAllInfoVOList) {
      if (!(this_present_busAllInfoVOList && that_present_busAllInfoVOList))
        return false;
      if (!this.busAllInfoVOList.equals(that.busAllInfoVOList))
        return false;
    }

    boolean this_present_busError = true && this.isSetBusError();
    boolean that_present_busError = true && that.isSetBusError();
    if (this_present_busError || that_present_busError) {
      if (!(this_present_busError && that_present_busError))
        return false;
      if (!this.busError.equals(that.busError))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_busAllInfoVOList = true && (isSetBusAllInfoVOList());
    list.add(present_busAllInfoVOList);
    if (present_busAllInfoVOList)
      list.add(busAllInfoVOList);

    boolean present_busError = true && (isSetBusError());
    list.add(present_busError);
    if (present_busError)
      list.add(busError);

    return list.hashCode();
  }

  @Override
  public int compareTo(QueryBusResp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBusAllInfoVOList()).compareTo(other.isSetBusAllInfoVOList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBusAllInfoVOList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.busAllInfoVOList, other.busAllInfoVOList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBusError()).compareTo(other.isSetBusError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBusError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.busError, other.busError);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryBusResp(");
    boolean first = true;

    sb.append("busAllInfoVOList:");
    if (this.busAllInfoVOList == null) {
      sb.append("null");
    } else {
      sb.append(this.busAllInfoVOList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("busError:");
    if (this.busError == null) {
      sb.append("null");
    } else {
      sb.append(this.busError);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (busError != null) {
      busError.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryBusRespStandardSchemeFactory implements SchemeFactory {
    public QueryBusRespStandardScheme getScheme() {
      return new QueryBusRespStandardScheme();
    }
  }

  private static class QueryBusRespStandardScheme extends StandardScheme<QueryBusResp> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryBusResp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BUS_ALL_INFO_VOLIST
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set16 = iprot.readSetBegin();
                struct.busAllInfoVOList = new HashSet<BusAllInfoVO>(2*_set16.size);
                BusAllInfoVO _elem17;
                for (int _i18 = 0; _i18 < _set16.size; ++_i18)
                {
                  _elem17 = new BusAllInfoVO();
                  _elem17.read(iprot);
                  struct.busAllInfoVOList.add(_elem17);
                }
                iprot.readSetEnd();
              }
              struct.setBusAllInfoVOListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BUS_ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.busError = new BusError();
              struct.busError.read(iprot);
              struct.setBusErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryBusResp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.busAllInfoVOList != null) {
        oprot.writeFieldBegin(BUS_ALL_INFO_VOLIST_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.busAllInfoVOList.size()));
          for (BusAllInfoVO _iter19 : struct.busAllInfoVOList)
          {
            _iter19.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.busError != null) {
        oprot.writeFieldBegin(BUS_ERROR_FIELD_DESC);
        struct.busError.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryBusRespTupleSchemeFactory implements SchemeFactory {
    public QueryBusRespTupleScheme getScheme() {
      return new QueryBusRespTupleScheme();
    }
  }

  private static class QueryBusRespTupleScheme extends TupleScheme<QueryBusResp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryBusResp struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBusAllInfoVOList()) {
        optionals.set(0);
      }
      if (struct.isSetBusError()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBusAllInfoVOList()) {
        {
          oprot.writeI32(struct.busAllInfoVOList.size());
          for (BusAllInfoVO _iter20 : struct.busAllInfoVOList)
          {
            _iter20.write(oprot);
          }
        }
      }
      if (struct.isSetBusError()) {
        struct.busError.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryBusResp struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set21 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.busAllInfoVOList = new HashSet<BusAllInfoVO>(2*_set21.size);
          BusAllInfoVO _elem22;
          for (int _i23 = 0; _i23 < _set21.size; ++_i23)
          {
            _elem22 = new BusAllInfoVO();
            _elem22.read(iprot);
            struct.busAllInfoVOList.add(_elem22);
          }
        }
        struct.setBusAllInfoVOListIsSet(true);
      }
      if (incoming.get(1)) {
        struct.busError = new BusError();
        struct.busError.read(iprot);
        struct.setBusErrorIsSet(true);
      }
    }
  }

}

